### ISSUE TITLE
More PDF manipulation options (Split, Rotate etc.)

### ISSUE THREAD

**Issue by nodecentral** [Fdawgs/docsmith#1085]
### Prerequisites

- [X] I have written a descriptive title
- [X] I have searched existing feature requests to ensure it has not already been proposed

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### Description

I’d like to request more .pdf manipulation options such as split, rotate, combine etc.. 

I’m often scanning documents in large batches, and rather than have to stop and start with each one to create file separations, it would be great to be able to scan everything all in at once and then run a split command (via an API) to break that batch out into individual documents be defining the splitting point e.g 2, 4, 6, 8 etc. ?

That way pages 1-2, 3-4, 5-6 are grouped and made separate.

**Comment by Fdawgs** [comment]
Hi @nodecentral, this is advanced manipulation that is beyond the scope of this API currently. This API's primary focus is converting documents from one format to another.

For your use case, your best approach is to the pdf-seperate [Poppler](https://poppler.freedesktop.org/) util via the CLI or via [node-poppler](https://github.com/Fdawgs/node-poppler.)

**Comment by nodecentral** [comment]
Thanks for responding @Fdawgs , I had seen [Poppler](https://hub.docker.com/r/minidocks/poppler) mentioned before, but I couldn’t find/work out how it all worked, and there didn’t seem to be much content online that explained how I’d get it up and running (e.g docker) and send requests to it? Are you using it in some capacity ?

**Comment by Fdawgs** [comment]
This API uses Poppler via [node-poppler](https://github.com/Fdawgs/node-poppler), and the Dockerfile installs the utils:
https://github.com/Fdawgs/docsmith/blob/0d01cc1ab9a0fd31152d2acf524423db48d328ed/Dockerfile#L10


You can do this yourself via the following:

Linux:
```bash
sudo apt-get install poppler-data poppler-utils
```

macOS:
```bash
brew install poppler
```

Windows:
Download binaries from https://github.com/oschwartz10612/poppler-windows

Then you can call them from the CLI, i.e.:
```bash
pdfseparate -h
```

CLI manpages: https://manpages.debian.org/bullseye/poppler-utils/

**Comment by nodecentral** [comment]
Thanks @Fdawgs, if I’m not pushing my luck,  I’d really like to find a Docker instance that I can set up that then make calls to via a rest api , to load specific pdf files from a network share and manipulate them - split, join, rotate etc. by any chance do you know of such a thing  ?

**Comment by Fdawgs** [comment]
Maybe https://github.com/gotenberg/gotenberg?

**Comment by nodecentral** [comment]
I did look at gotenburg first, but from what I could tell, that doesn’t seem to support a pdf split option, which is a key requirement..  At least not that I could see ?

**Comment by Fdawgs** [comment]
No idea then, sorry!
