### ISSUE TITLE
Blank CORS_ORIGIN in .env does not default to false - crashes app instead.

### ISSUE THREAD

**Issue by NHS-juju** [Fdawgs/docsmith#1384]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### API/app/plugin version

10.0.12

### Node.js version

v18.15.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10

### Description

Attempting to run the app while leaving the "CORS_ORIGN" parameter blank in .env will result in a crash in [src/config/index.js](https://github.com/Fdawgs/docsmith/blob/main/src/config/index.js)

Unlike [Line 186](https://github.com/Fdawgs/docsmith/blob/main/src/config/index.js#L186) which grabs the parameter direct from .env, [Line 187](https://github.com/Fdawgs/docsmith/blob/main/src/config/index.js#L187) makes use of the [parseCorsParameter function](https://github.com/Fdawgs/docsmith/blob/main/src/config/index.js#L21) to parse string booleans into actual booleans.

If the value "CORS_MAX_AGE" from .env is undefined, the short circuit in [Line 186](https://github.com/Fdawgs/docsmith/blob/main/src/config/index.js#L186) can take effect. However, a null parameter passed into the function on [Line 187](https://github.com/Fdawgs/docsmith/blob/main/src/config/index.js#L187) will fail when attempting to evaluate the undefined, so will never make use of the subsequent short circuit

### Steps to Reproduce

Run the app with "CORS_ORIGIN" left blank in .env

**Comment by NHS-juju** [comment]
Accidentally marked as closed, but is only resolved in local fork.

**Comment by Fdawgs** [comment]
Cheers @NHS-juju, this week I've been revisiting the plugins and routes for all my APIs, and their unit tests, and have flushed out a more few bugs.

Will take a look at the config and main server pieces of them all next week!
